#!/bin/sh
#
# @name Gazebo zhiyuan
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=mctilt}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 16
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.3415
param set-default CA_ROTOR0_PY 0.4823
param set-default CA_ROTOR0_PZ 0
param set-default CA_ROTOR0_CT  10
param set-default CA_ROTOR0_KM  0.03

param set-default CA_ROTOR1_PX -0.3415
param set-default CA_ROTOR1_PY -0.4823
param set-default CA_ROTOR1_PZ 0
param set-default CA_ROTOR1_CT  10
param set-default CA_ROTOR1_KM  0.03

param set-default CA_ROTOR2_PX 0.3415
param set-default CA_ROTOR2_PY -0.4823
param set-default CA_ROTOR2_PZ 0
param set-default CA_ROTOR2_CT  10
param set-default CA_ROTOR2_KM -0.03

param set-default CA_ROTOR3_PX -0.3415
param set-default CA_ROTOR3_PY 0.4823
param set-default CA_ROTOR3_PZ 0
param set-default CA_ROTOR3_CT  10
param set-default CA_ROTOR3_KM -0.03

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 50
param set-default SIM_GZ_EC_MIN2 50
param set-default SIM_GZ_EC_MIN3 50
param set-default SIM_GZ_EC_MIN4 50

param set-default SIM_GZ_EC_MAX1 750
param set-default SIM_GZ_EC_MAX2 750
param set-default SIM_GZ_EC_MAX3 750
param set-default SIM_GZ_EC_MAX4 750

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204

param set-default SIM_GZ_SV_MAXA1 90
param set-default SIM_GZ_SV_MAXA2 90
param set-default SIM_GZ_SV_MAXA3 90
param set-default SIM_GZ_SV_MAXA4 90

param set-default SIM_GZ_SV_MINA1 -90
param set-default SIM_GZ_SV_MINA2 -90
param set-default SIM_GZ_SV_MINA3 -90
param set-default SIM_GZ_SV_MINA4 -90

param set-default MPC_THR_HOVER 0.5
param set-default NAV_DLL_ACT 2

param set-default MPC_Z_P 0.65
param set-default MPC_XY_P 0.40
param set-default MPC_Z_VEL_P_ACC 3.50
param set-default MPC_Z_VEL_I_ACC 0.30
param set-default MPC_Z_VEL_D_ACC 0.05
param set-default MPC_XY_VEL_P_ACC 1.65
param set-default MPC_XY_VEL_I_ACC 1.00
param set-default MPC_XY_VEL_D_ACC 0.25

param set-default MC_PITCH_P 1.50
param set-default MC_ROLL_P 2.50
param set-default MC_YAW_P 4.00

param set-default MC_ROLLRATE_P 0.0746
param set-default MC_ROLLRATE_I 0.15
param set-default MC_ROLLRATE_D 0.0042
param set-default MC_ROLLRATE_K 1.45

param set-default MC_ROLLRATE_P 0.0574
param set-default MC_ROLLRATE_I 0.1250
param set-default MC_ROLLRATE_D 0.0056
param set-default MC_ROLLRATE_K 1.00

param set-default MC_ROLLRATE_P 0.2053
param set-default MC_ROLLRATE_I 0.08
param set-default MC_ROLLRATE_D 0.0119
param set-default MC_ROLLRATE_K 0.80
