#!/bin/sh
#
# @name Gazebo thrust_vector
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=thrust_vector}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 16
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.1315
param set-default CA_ROTOR0_PY -0.1315
param set-default CA_ROTOR0_PZ 0
param set-default CA_ROTOR0_CT  10
param set-default CA_ROTOR0_KM -0.02

param set-default CA_ROTOR1_PX -0.1315
param set-default CA_ROTOR1_PY 0.1315
param set-default CA_ROTOR1_PZ 0
param set-default CA_ROTOR1_CT  10
param set-default CA_ROTOR1_KM -0.02

param set-default CA_ROTOR2_PX -0.1315
param set-default CA_ROTOR2_PY -0.1315
param set-default CA_ROTOR2_PZ 0
param set-default CA_ROTOR2_CT  10
param set-default CA_ROTOR2_KM 0.02

param set-default CA_ROTOR3_PX 0.1315
param set-default CA_ROTOR3_PY 0.1315
param set-default CA_ROTOR3_PZ 0
param set-default CA_ROTOR3_CT  10
param set-default CA_ROTOR3_KM 0.02

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 100
param set-default SIM_GZ_EC_MIN2 100
param set-default SIM_GZ_EC_MIN3 100
param set-default SIM_GZ_EC_MIN4 100

param set-default SIM_GZ_EC_MAX1 1500
param set-default SIM_GZ_EC_MAX2 1500
param set-default SIM_GZ_EC_MAX3 1500
param set-default SIM_GZ_EC_MAX4 1500

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_FUNC5 205
param set-default SIM_GZ_SV_FUNC6 206
param set-default SIM_GZ_SV_FUNC7 207
param set-default SIM_GZ_SV_FUNC8 208

param set-default SIM_GZ_SV_MAXA1 90
param set-default SIM_GZ_SV_MAXA2 90
param set-default SIM_GZ_SV_MAXA3 90
param set-default SIM_GZ_SV_MAXA4 90
param set-default SIM_GZ_SV_MAXA5 90
param set-default SIM_GZ_SV_MAXA6 90
param set-default SIM_GZ_SV_MAXA7 90
param set-default SIM_GZ_SV_MAXA8 90

param set-default SIM_GZ_SV_MINA1 -90
param set-default SIM_GZ_SV_MINA2 -90
param set-default SIM_GZ_SV_MINA3 -90
param set-default SIM_GZ_SV_MINA4 -90
param set-default SIM_GZ_SV_MINA5 -90
param set-default SIM_GZ_SV_MINA6 -90
param set-default SIM_GZ_SV_MINA7 -90
param set-default SIM_GZ_SV_MINA8 -90

param set-default MPC_THR_HOVER 0.4
param set-default NAV_DLL_ACT 2
