#!/bin/sh
#
# @name Thrust Vector
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#
. ${R}etc/init.d/rc.mc_defaults

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.1315
param set-default CA_ROTOR0_PY -0.1315
param set-default CA_ROTOR0_PZ 0
param set-default CA_ROTOR0_CT  10
param set-default CA_ROTOR0_KM -0.05

param set-default CA_ROTOR1_PX -0.1315
param set-default CA_ROTOR1_PY 0.1315
param set-default CA_ROTOR1_PZ 0
param set-default CA_ROTOR1_CT  10
param set-default CA_ROTOR1_KM -0.05

param set-default CA_ROTOR2_PX -0.1315
param set-default CA_ROTOR2_PY -0.1315
param set-default CA_ROTOR2_PZ 0
param set-default CA_ROTOR2_CT  10
param set-default CA_ROTOR2_KM 0.05

param set-default CA_ROTOR3_PX 0.1315
param set-default CA_ROTOR3_PY 0.1315
param set-default CA_ROTOR3_PZ 0
param set-default CA_ROTOR3_CT  10
param set-default CA_ROTOR3_KM 0.05

param set-default TRV_THR_HOVER 0.4
param set-default NAV_DLL_ACT 2

param set JOICAN_ENABLE 3

param set JOICAN_SV_FUNC1 201
param set JOICAN_SV_FUNC2 202
param set JOICAN_SV_FUNC3 203
param set JOICAN_SV_FUNC4 204
param set JOICAN_SV_FUNC5 205
param set JOICAN_SV_FUNC6 206
param set JOICAN_SV_FUNC7 207
param set JOICAN_SV_FUNC8 208

param set-default JOICAN_C1S1_OFF 0
param set-default JOICAN_C1S2_OFF 0
param set-default JOICAN_C1S3_OFF 0
param set-default JOICAN_C1S4_OFF 0

param set-default JOICAN_C2S1_OFF 0
param set-default JOICAN_C2S2_OFF 0
param set-default JOICAN_C2S3_OFF 0
param set-default JOICAN_C2S4_OFF 0

param set-default JOICAN_C1S1_REV 0
param set-default JOICAN_C1S2_REV 0
param set-default JOICAN_C1S3_REV 0
param set-default JOICAN_C1S4_REV 0

param set-default JOICAN_C2S1_REV 0
param set-default JOICAN_C2S2_REV 0
param set-default JOICAN_C2S3_REV 0
param set-default JOICAN_C2S4_REV 0
